
[mobs]
	blacklist = []
	whitelist = ["minecraft:chicken", "minecraft:pig", "minecraft:cow", "minecraft:turtle", "minecraft:fox", "minecraft:glow_squid", "minecraft:squid", "minecraft:allay", "minecraft:axolotl", "minecraft:bat", "minecraft:cat", "minecraft:cod", "minecraft:donkey", "minecraft:frog", "minecraft:horse", "minecraft:mooshroom", "minecraft:mule", "minecraft:ocelot", "minecraft:parot", "minecraft:pufferfish", "minecraft:rabbit", "minecraft:salmon", "minecraft:sheep", "minecraft:skeleton_horse", "minecraft:strider", "minecraft:tadpole", "minecraft:tropical_fish", "minecraft:wandering_villager", "minecraft:bee", "minecraft:dolphin", "minecraft:goat", "minecraft:llama", "minecraft:panda", "minecraft:polar_bear", "minecraft:wolf", "minecraft:zombie_horse", "minecraft:villager", "minecraft:trader_llama"]
	always_show_level = false
	show_level_when_looking_at = true
	exp_bonus_per_level = 0.1
	hidden_levels = []

[attributes]
	attribute_bonuses = [["minecraft:generic.movement_speed", 0.001], ["minecraft:generic.flying_speed", 0.001], ["minecraft:generic.attack_damage", 0.1], ["minecraft:generic.armor", 0.1], ["minecraft:generic.max_health", 0.1], ["autoleveling:monster.projectile_damage_bonus", 0.1], ["autoleveling:monster.explosion_damage_bonus", 0.1]]

[default_leveling_settings]
	starting_level = 1
	max_level = 100
	levels_per_distance = 0.001
	levels_per_deepness = 0.0
	random_level_bonus = 0
	levels_per_day = 0.0
	level_power_per_distance = 0.1
	level_power_per_deepness = 0.0

