
["Tweak Settings"]
	#setting this to true will allows baby leviathan to grow into an adult
	canBabyLeviathanGrow = true
	#item used for grow baby leviathan to adult
	leviathanGrowItem = "minecraft:dragon_egg"
	#item used for tame baby leviathan
	leviathanTameItem = "minecraft:tropical_fish"
	#setting this to true will allows modern remnant to grow into an ancient remnant
	canModernRemnantGrow = true
	#item used for grow modern remnant to ancient remnant
	remnantGrowItem = "minecraft:brush"
	#item used for tame modern remnant
	remnantTameItem = "minecraft:sniffer_egg"
	#second until baby leviathan hatch
	abyssalEggHatchTime = 12000

